### ISSUE TITLE
Seven Theme - Airports

### ISSUE THREAD

**Issue by BossOfGames** [BossOfGames/phpvms#1]

**Comment by BossOfGames** [comment]
@arthurpar06 I may want to add an enhancement to this one. Right now there's no `/airports` route on the system. Should we consider adding that with a search on that page?

What are your thoughts?

**Comment by arthurpar06** [comment]
Why not, but it might be better to handle it in another PR after this one. The main goal of the seven project is to add a new theme, and adding new routes might be out of scope, so it could be better suited for a future PR

**Comment by ArthurHetem** [comment]
![image](https://github.com/user-attachments/assets/5f3d815b-f553-4779-b378-3604c7198d66)

**Comment by BossOfGames** [comment]
Looks good!
