### ISSUE TITLE
Seven Theme - Errors

### ISSUE THREAD

**Issue by BossOfGames** [BossOfGames/phpvms#13]

**Comment by arthurpar06** [comment]
![image](https://github.com/user-attachments/assets/329a322a-eaf9-460e-a1ff-3b90ff299af0)
![image](https://github.com/user-attachments/assets/5cc770e6-87d7-4f39-a4be-c50f09281c58)
![image](https://github.com/user-attachments/assets/7de96651-fbda-4d37-bb03-7543ede56e2e)
![image](https://github.com/user-attachments/assets/96525915-8a7e-4d35-afba-4772b35be213)

**Comment by BossOfGames** [comment]
Those look fantastic.

For the 503, let's not extend the default view, and instead let's go for a full bleed and center everything.

Also, for maintenance mode, it's possible to set a message, AFAIK, so we could also look into showing that.

**Comment by BossOfGames** [comment]
Adjusted the 500 error page:
![image](https://github.com/user-attachments/assets/8a551d83-b260-4b55-a6ba-0c7b9bacb626)

**Comment by arthurpar06** [comment]
![Image](https://github.com/user-attachments/assets/60f6ab12-5a13-48bd-8f2d-2131064eca1c)
I don't see anything that looks like a message we could set.

**Comment by BossOfGames** [comment]
@arthurpar06 would this be viable? https://stackoverflow.com/questions/39421944/laravel-display-a-custom-message-in-maintenance-mode

Also, just realized too, we might want to make the 500 error page like the 503 page, because if the error is something related to a mistake in the theme, we could get into an ungraceful 500 error loop.

**Comment by arthurpar06** [comment]
But can you add the `--message flag`? When I try, I just get `The "--message" option does not exist.`...

I'm not sure what you mean by an ungraceful 500 error loop. Since this page is just basic HTML, I don't see how it could trigger a 500 error loop. I mean, it's almost the same as before, we just added a simple div to help people out (inspired by Dispo's theme)

**Comment by BossOfGames** [comment]
> But can you add the `--message flag`? When I try, I just get `The "--message" option does not exist.`...
> 
> I'm not sure what you mean by an ungraceful 500 error loop. Since this page is just basic HTML, I don't see how it could trigger a 500 error loop. I mean, it's almost the same as before, we just added a simple div to help people out (inspired by Dispo's theme)


We're extending app last I checked. If there's an error in the app.blade or its includes, there in lies the problem :)

**Comment by BossOfGames** [comment]
Fair enough on the 503. Let's keep as is.

**Comment by arthurpar06** [comment]
Ohh mb didn't see you changed the 503

**Comment by arthurpar06** [comment]
> > But can you add the `--message flag`? When I try, I just get `The "--message" option does not exist.`...
> > I'm not sure what you mean by an ungraceful 500 error loop. Since this page is just basic HTML, I don't see how it could trigger a 500 error loop. I mean, it's almost the same as before, we just added a simple div to help people out (inspired by Dispo's theme)
> 
> We're extending app last I checked. If there's an error in the app.blade or its includes, there in lies the problem :)

I just tested it, and in this case, it returns the default Symfony error page, so there's no weird loop
![image](https://github.com/user-attachments/assets/6bc1d20b-9321-413b-a4b1-c3fba230bff2)

**Comment by BossOfGames** [comment]
> Ohh mb didn't see you changed the 503

Yep. I changed the 503 because if the site is in maintenance mode, there's no need to give the user links to browse it :)

If a webmaster studies Laravel, I think they would know how to make some routes show up normal while in maintenance mode. In that case, they would also be running their own theme with that carve out in mind.

**Comment by BossOfGames** [comment]
> > > But can you add the `--message flag`? When I try, I just get `The "--message" option does not exist.`...
> > > I'm not sure what you mean by an ungraceful 500 error loop. Since this page is just basic HTML, I don't see how it could trigger a 500 error loop. I mean, it's almost the same as before, we just added a simple div to help people out (inspired by Dispo's theme)
> > 
> > 
> > We're extending app last I checked. If there's an error in the app.blade or its includes, there in lies the problem :)
> 
> I just tested it, and in this case, it returns the default Symfony error page, so there's no weird loop ![image](https://private-user-images.githubusercontent.com/41431456/398924005-6bc1d20b-9321-413b-a4b1-c3fba230bff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyOTgwNjQsIm5iZiI6MTczNTI5Nzc2NCwicGF0aCI6Ii80MTQzMTQ1Ni8zOTg5MjQwMDUtNmJjMWQyMGItOTMyMS00MTNiLWE0YjEtYzNmYmEyMzBiZmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDExMDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMDdiM2VlOTdlZjMzOTJlNGU0YzdmYTY0NTFjMjExZGFhOTdlZjk0OWM1MzVjYTUyMmI0ZDllZDVkZDRmYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.68qazRQ2ZwqF9hq04Ry4tm4M0HEAQAGtU_ttCMH8WJk)

Ok, good to know. I guess it would be up to our choice then if we want to show a graceful error explaining what to do, or a error that doesn't explain what to do.

I'll trust your judgement. We can keep it the same if that's preferred.

**Comment by arthurpar06** [comment]
IMO a 500 error is something that often happens on a single page; it's rarely related to the main app or the nav because those are well-tested and onlly handle basic tasks. So having links to go back or change pages might be great to help users "get out" of the 500 error. 

Additionally, providing details on how to debug the issue might be helpful for less experienced developers and it could save some precious time on discord if they read it and directly send their logs.

**Comment by BossOfGames** [comment]
Ok, I'm good with that. We'll call this issue done then.
