### ISSUE TITLE
Seven Theme - Home

### ISSUE THREAD

**Issue by ArthurHetem** [BossOfGames/phpvms#18]

**Comment by ArthurHetem** [comment]
![image](https://github.com/user-attachments/assets/c449235e-ae67-4970-b12e-880ada6fe546)

**Comment by BossOfGames** [comment]
Do we want to do anything more with Home? I feel like this is one of those pages that was created to simply show data. That's also reflective of the HomeController, only returning the newest pilots.

I feel like there could be more here.

**Comment by ArthurHetem** [comment]
Yeah, we can probably add the news there too

**Comment by BossOfGames** [comment]
> Yeah, we can probably add the news there too

I like that idea. I'll close this issue for now as completed. I have a news system enhancement in the works. This would be an excellent idea to put in here, once that PR is in.
